name: metalearn_a2c_binary_controller_depth
experiment_type: METALEARN_REINFORCE
description: 'metalearning with A2C architecture: controller depth experiments'
created_at: 2020-03-03-21-37-52
git_hash: 677b7cc
parameters:
  datasets: null
  test_datasets: null
  output_fp: /output
  input_size: 60
  hidden_size: 60
  output_size: 60
  n_layers: 3
  dropout_rate: 0.2
  entropy_coef: 0.0
  entropy_coef_anneal_to: 0.0
  entropy_coef_anneal_by: null
  normalize_reward: true
  gamma: 0.99
  meta_reward_multiplier: 1.0
  n_episodes: 100
  n_iter: 16
  learning_rate: 0.005
  optim_beta1: 0.9
  optim_beta2: 0.999
  env_sources:
  - SKLEARN
  - OPEN_ML
  - KAGGLE
  test_env_sources:
  - AUTOSKLEARN_BENCHMARK
  n_eval_iter: 10
  target_types:
  - BINARY
  - MULTICLASS
  test_env_target_types:
  - BINARY
  - MULTICLASS
  test_set_config:
    AUTOSKLEARN_BENCHMARK:
      random_state: 100
      test_size: 0.8
    SKLEARN:
      random_state: 100
      test_size: 0.8
  error_reward: 0
  n_samples: 5000
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
  hyperparameters:
    n_layers:
    - 3
    - 6
    - 9
    - 12
