name: openml_cache_test
experiment_type: METALEARN_REINFORCE
description: test out caching of openml datasets
created_at: 2020-01-26-14-13-09
git_hash: ae0437a
parameters:
  datasets: null
  test_datasets: null
  output_fp: /output
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  entropy_coef: 0.0
  entropy_coef_anneal_to: 0.0
  entropy_coef_anneal_by: null
  normalize_reward: true
  gamma: 0.99
  meta_reward_multiplier: 1.0
  n_episodes: 3
  n_iter: 3
  learning_rate: 0.005
  optim_beta1: 0.9
  optim_beta2: 0.999
  env_sources:
  - OPEN_ML
  - AUTOSKLEARN_BENCHMARK
  test_env_sources:
  - OPEN_ML_BENCHMARK_CC18
  n_eval_iter: 3
  target_types:
  - BINARY
  - MULTICLASS
  test_env_target_types:
  - BINARY
  - MULTICLASS
  test_set_config:
    AUTOSKLEARN_BENCHMARK:
      random_state: 100
      test_size: 0.8
    SKLEARN:
      random_state: 100
      test_size: 0.8
  error_reward: 0
  n_samples: 5000
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
