name: metalearn_a2c_binary_multiclass_regression
experiment_type: METALEARN_REINFORCE
description: metalearn with A2C on binary, multiclass, regression tasks
created_at: 2020-01-31-21-11-49
git_hash: ae0437a
parameters:
  datasets: null
  test_datasets: null
  output_fp: /output
  input_size: 60
  hidden_size: 60
  output_size: 60
  n_layers: 3
  dropout_rate: 0.2
  entropy_coef: 0.1
  entropy_coef_anneal_to: 0.0
  entropy_coef_anneal_by: null
  normalize_reward: False
  gamma: 0.99
  meta_reward_multiplier: 1.0
  n_episodes: 1000
  n_iter: 50
  n_eval_iter: 50
  learning_rate: 0.005
  optim_beta1: 0.9
  optim_beta2: 0.999
  env_sources:
  - SKLEARN
  - OPEN_ML
  - AUTOSKLEARN_BENCHMARK
  test_env_sources:
  - OPEN_ML_BENCHMARK_CC18
  - KAGGLE
  target_types:
  - BINARY
  - MULTICLASS
  - REGRESSION
  test_env_target_types:
  - BINARY
  - MULTICLASS
  - REGRESSION
  error_reward: -1
  n_samples: 10000
  per_framework_time_limit: 360
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
  hyperparameters:
    learning_rate:
    - 0.0
    - 0.00005
    - 0.0005
    - 0.005
